export const NAV = {
  convert: [
    { href: "/", label: "Все форматы" },
    { href: "/heic-to-jpeg", label: "HEIC → JPEG" },
    { href: "/heic-to-png", label: "HEIC → PNG" },
    { href: "/jpeg-to-png", label: "JPEG → PNG" },
    { href: "/jpeg-to-webp", label: "JPEG → WebP" },
    { href: "/jpeg-to-avif", label: "JPEG → AVIF" },
    { href: "/png-to-webp", label: "PNG → WebP" },
    { href: "/png-to-avif", label: "PNG → AVIF" },
    { href: "/webp-to-jpeg", label: "WebP → JPEG" },
    { href: "/webp-to-png", label: "WebP → PNG" },
    { href: "/heic-to-pdf", label: "HEIC → PDF" },
    { href: "/image-to-ico", label: "Image → Favicon (ICO)" },
  ],
  webp: [
    { href: "/webp-to-png", label: "WebP → PNG" },
    { href: "/webp-to-jpeg", label: "WebP → JPEG" },
    { href: "/webp-to-avif", label: "WebP → AVIF" },
    { href: "/webp-to-pdf", label: "WebP → PDF" },
  ],
  png: [
    { href: "/png-to-webp", label: "PNG → WebP" },
    { href: "/png-to-jpeg", label: "PNG → JPEG" },
    { href: "/png-to-avif", label: "PNG → AVIF" },
    { href: "/png-to-pdf", label: "PNG → PDF" },
  ],
  jpeg: [
    { href: "/jpeg-to-webp", label: "JPEG → WebP" },
    { href: "/jpeg-to-png", label: "JPEG → PNG" },
    { href: "/jpeg-to-avif", label: "JPEG → AVIF" },
    { href: "/jpeg-to-pdf", label: "JPEG → PDF" },
  ],
  avif: [
    { href: "/avif-to-jpeg", label: "AVIF → JPEG" },
    { href: "/avif-to-png", label: "AVIF → PNG" },
    { href: "/avif-to-webp", label: "AVIF → WebP" },
  ],
  heic: [
    { href: "/heic-to-jpeg", label: "HEIC → JPEG" },
    { href: "/heic-to-png", label: "HEIC → PNG" },
    { href: "/heic-to-webp", label: "HEIC → WebP" },
    { href: "/heic-to-pdf", label: "HEIC → PDF" },
  ],
  favicon: [{ href: "/image-to-ico", label: "Image → Favicon (ICO)" }],
  language: [
    { href: "/ru", label: "Русский" },
    { href: "/en", label: "English" },
    { href: "/es", label: "Español" },
    { href: "/de", label: "Deutsch" },
  ],
};
